config env

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -23,10 +23,18 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Verify Dockerfile
+        run: |
+          if [ ! -f ./Docker/Dockerfile ]; then
+            echo "❌ Dockerfile not found in ./Docker"
+            exit 1
+          fi
+          echo "✅ Dockerfile found."
+
       - name: Build and push Moodle Docker image
         uses: docker/build-push-action@v6
         with:
-          context: .
+          context: ./Docker
           push: true
           tags: |
             ghcr.io/${{ github.repository_owner }}/moodle:latest
